import { Navigation } from '@/components/navigation'
import { Footer } from '@/components/footer'

export default function PrivacyPolicyPage() { return <div className="min-h-screen bg-background"><Navigation /><main><section className="border-b border-border bg-muted/30"><div className="mx-auto max-w-4xl px-6 py-20 sm:px-8 lg:py-28"><p className="text-sm font-semibold uppercase tracking-[0.14em] text-secondary">Legal</p><h1 className="mt-4 text-5xl font-semibold tracking-[-0.04em] sm:text-6xl">Privacy policy.</h1><p className="mt-6 text-lg text-muted-foreground">Last updated September 19, 2026</p></div></section><section className="mx-auto max-w-4xl px-6 py-16 sm:px-8 lg:py-24"><div className="grid gap-12">
  <article><h2 className="text-2xl font-semibold">What Preflight checks, and what it keeps</h2><p className="mt-4 leading-8 text-muted-foreground">Preflight examines the links and creatives you ask it to check: where a link ends up after redirects, how quickly it responds, and whether an image meets the dimensions you expect. The results are held in your browser, on your device, and a report of your last check is kept only until the next one or until its expiry clears it.</p></article>
  <article><h2 className="text-2xl font-semibold">Network activity</h2><p className="mt-4 leading-8 text-muted-foreground">Checking a link means requesting it — the same request your browser would make if you clicked it. Preflight follows redirects, measures the response, and reads just enough of the destination to know it answered. Your check results never leave your browser. The extension contacts exactly one website of its own: the Preflight product site, which hosts the release notes it opens after updates. That site keeps a record of the installed version so the notes match what you are running, and nothing else.</p></article>
  <article><h2 className="text-2xl font-semibold">Sharing</h2><p className="mt-4 leading-8 text-muted-foreground">Your checks, links, and results are never sold, rented, or traded, and never shared with third parties. There is no account, no upload, and no analytics.</p></article>
  <article><h2 className="text-2xl font-semibold">Permissions and why they are needed</h2><div className="mt-6 grid gap-5"><p className="leading-8 text-muted-foreground"><strong className="text-foreground">storage</strong> — holds your last check report and your settings on your device; nothing is ever written to a server.</p><p className="leading-8 text-muted-foreground"><strong className="text-foreground">alarms</strong> — wakes the extension periodically to clear stale check reports, so an old result is never mistaken for a fresh one, and to check its own website for release notes.</p><p className="leading-8 text-muted-foreground"><strong className="text-foreground">webRequest and site access</strong> — a campaign can point anywhere, so checking links means being able to request any destination you paste in. Preflight reads responses, never sends your data anywhere, and requests nothing without you asking it to check a link.</p></div></article>
  <article><h2 className="text-2xl font-semibold">Children</h2><p className="mt-4 leading-8 text-muted-foreground">Preflight is a tool for advertisers and is not directed at children. It collects no personal information from anyone.</p></article>
  <article><h2 className="text-2xl font-semibold">Changes to this policy</h2><p className="mt-4 leading-8 text-muted-foreground">If this policy changes, the updated version is published on this page with a new date at the top. Continuing to use the extension after a change means you accept the revised policy.</p></article>
</div></section></main><Footer /></div> }
